import { SUBMISSION_STATUS } from "../../models/submission.model.js";
import { ROLES } from "../../constants/role.constant.js";


const VALID_TRANSITIONS = new Map([
    [SUBMISSION_STATUS.DRAFT, new Set([SUBMISSION_STATUS.SUBMITTED])],
    [SUBMISSION_STATUS.SUBMITTED, new Set([SUBMISSION_STATUS.UNDER_REVIEW, SUBMISSION_STATUS.WITHDRAWN])],
    [SUBMISSION_STATUS.UNDER_REVIEW, new Set([SUBMISSION_STATUS.ACCEPTED, SUBMISSION_STATUS.REJECTED, SUBMISSION_STATUS.CLARIFICATION])],
    [SUBMISSION_STATUS.CLARIFICATION, new Set([SUBMISSION_STATUS.SUBMITTED, SUBMISSION_STATUS.WITHDRAWN])],
    [SUBMISSION_STATUS.ACCEPTED, new Set([SUBMISSION_STATUS.PILOT_PROPOSED])],
    [SUBMISSION_STATUS.PILOT_PROPOSED, new Set([SUBMISSION_STATUS.PILOT_ACTIVE])],
    [SUBMISSION_STATUS.PILOT_ACTIVE, new Set([SUBMISSION_STATUS.PILOT_COMPLETED])],
    [SUBMISSION_STATUS.PILOT_COMPLETED, new Set([SUBMISSION_STATUS.SCALED, SUBMISSION_STATUS.CLOSED])],
    [SUBMISSION_STATUS.SCALED, new Set([SUBMISSION_STATUS.CLOSED])],
    [SUBMISSION_STATUS.REJECTED, new Set([SUBMISSION_STATUS.CLOSED])],
    [SUBMISSION_STATUS.WITHDRAWN, new Set([SUBMISSION_STATUS.CLOSED])],
]);


const TRANSITION_ROLES = new Map([
    [`${SUBMISSION_STATUS.DRAFT}→${SUBMISSION_STATUS.SUBMITTED}`, new Set([ROLES.STARTUP_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.SUBMITTED}→${SUBMISSION_STATUS.WITHDRAWN}`, new Set([ROLES.STARTUP_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.CLARIFICATION}→${SUBMISSION_STATUS.SUBMITTED}`, new Set([ROLES.STARTUP_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.CLARIFICATION}→${SUBMISSION_STATUS.WITHDRAWN}`, new Set([ROLES.STARTUP_USER, ROLES.ADMIN])],

    // Reviewer/Gov-driven
    [`${SUBMISSION_STATUS.SUBMITTED}→${SUBMISSION_STATUS.UNDER_REVIEW}`, new Set([ROLES.GOVERNMENT_USER, ROLES.EVALUATOR, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.UNDER_REVIEW}→${SUBMISSION_STATUS.ACCEPTED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.UNDER_REVIEW}→${SUBMISSION_STATUS.REJECTED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.UNDER_REVIEW}→${SUBMISSION_STATUS.CLARIFICATION}`, new Set([ROLES.GOVERNMENT_USER, ROLES.EVALUATOR, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.ACCEPTED}→${SUBMISSION_STATUS.PILOT_PROPOSED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.PILOT_PROPOSED}→${SUBMISSION_STATUS.PILOT_ACTIVE}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.PILOT_ACTIVE}→${SUBMISSION_STATUS.PILOT_COMPLETED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.PILOT_COMPLETED}→${SUBMISSION_STATUS.SCALED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.PILOT_COMPLETED}→${SUBMISSION_STATUS.CLOSED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.SCALED}→${SUBMISSION_STATUS.CLOSED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.REJECTED}→${SUBMISSION_STATUS.CLOSED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
    [`${SUBMISSION_STATUS.WITHDRAWN}→${SUBMISSION_STATUS.CLOSED}`, new Set([ROLES.GOVERNMENT_USER, ROLES.ADMIN])],
]);


export function canTransition(fromStatus, toStatus) {
    const allowed = VALID_TRANSITIONS.get(fromStatus);
    return allowed ? allowed.has(toStatus) : false;
}


export function assertTransition({ fromStatus, toStatus, actorRole }) {
    if (!canTransition(fromStatus, toStatus)) {
        const error = new Error(`Invalid transition: ${fromStatus} → ${toStatus}`);
        error.statusCode = 400;
        error.code = "INVALID_TRANSITION";
        throw error;
    }

    const key = `${fromStatus}→${toStatus}`;
    const allowedRoles = TRANSITION_ROLES.get(key);

    if (!allowedRoles || !allowedRoles.has(actorRole)) {
        const error = new Error(`Role ${actorRole} is not permitted to transition from ${fromStatus} to ${toStatus}`);
        error.statusCode = 403;
        error.code = "TRANSITION_FORBIDDEN";
        throw error;
    }
}
